[tool.poetry]
name = "artis3n.tailscale"
version = "4.1.0"
description = "Ansible role to install and enable a Tailscale node."
authors = ["Artis3n <dev@artis3nal.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.11"
ansible = "^8.4.0"

[tool.poetry.group.dev.dependencies]
ansible-lint = { version = "^6.22.0", markers = "platform_system != 'Windows'" }
molecule = "^6.0.2"
molecule-plugins = {extras = ["docker"], version = "^23.5.0"}
pre-commit = "^3.4.0"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
