[tool.poetry]
name = "artis3n.tailscale"
version = "2.0.1"
description = "Ansible role to install and enable a Tailscale node."
authors = ["Artis3n <dev@artis3nal.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
ansible = "^6.3.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.20.0"
ansible-lint = "^6.4.0"
molecule = {extras = ["docker"], version = "^4.0.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
