---
- name: Debian | Apt Dependencies
  become: true
  apt:
    name: "{{ apt_dependencies }}"
    state: present
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: Debian | Legacy Apt Dependencies
  become: true
  apt:
    name: "{{ legacy_apt_dependencies }}"
  when:
    - ansible_distribution_major_version | int < 11
    - ansible_distribution_major_version != "testing"

- name: Debian | Tailscale Signing Key
  become: true
  apt_key:
    url: "{{ apt_signkey }}"
    state: present

- name: Debian | Add Tailscale Deb
  become: true
  apt_repository:
    repo: "{{ apt_deb }}"
    state: present
  register: tailscale_apt_repo_result

- name: Debian | Install Tailscale
  become: true
  apt:
    name: "{{ tailscale_package }}"
    state: latest
    update_cache: "{{ tailscale_apt_repo_result.changed }}"
