---
- name: Debian | Apt Update
  become: yes
  apt:
    update_cache: yes

- name: Debian | Apt Dependencies
  become: yes
  apt:
    name: "{{ apt_dependencies }}"
    state: present

- name: Debian | Legacy Apt Dependencies
  become: yes
  apt:
    name: "{{ legacy_apt_dependencies }}"
  when: ansible_distribution_major_version < 20

- name: Debian | Tailscale Signing Key
  become: yes
  apt_key:
    url: "{{ apt_signkey }}"
    state: present

- name: Debian | Add Tailscale Deb
  become: yes
  apt_repository:
    repo: "{{ apt_deb }}"
    state: present

- name: Debian | Install Tailscale
  become: yes
  apt:
    name: "{{ tailscale_package }}"
    state: present
    update_cache: yes
