---
- name: Install | CentOS and related families
  when: >
    ansible_distribution in tailscale_centos_family_distros
    or (ansible_distribution == 'Amazon' and ansible_distribution_major_version | int < 2023)
  ansible.builtin.include_tasks: centos/install.yml

- name: Install | Debian and related families
  when: ansible_distribution in tailscale_debian_family_distros
  ansible.builtin.include_tasks: debian/install.yml

- name: Install | Fedora and related families
  when: >
    ansible_distribution == 'Fedora'
    or (ansible_distribution == 'Amazon' and ansible_distribution_major_version | int >= 2023)
  ansible.builtin.include_tasks: fedora/install.yml

- name: Install | Arch
  when: ansible_distribution == 'Archlinux'
  ansible.builtin.include_tasks: arch/install.yml

- name: Install | OpenSUSE
  when: ansible_distribution in tailscale_opensuse_family_distros
  ansible.builtin.include_tasks: opensuse/install.yml

- name: Install | Remove legacy state folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.artis3n-tailscale"
    state: absent

- name: Install | Determine state folder
  ansible.builtin.set_fact:
    # Following https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
    tailscale_state_folder: "{{ ansible_env.XDG_STATE_HOME | default(ansible_env.HOME + '/.local/state') }}"

- name: Install | Set state idempotency folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: '0700'
  loop:
    - "{{ tailscale_state_folder }}"
    - "{{ tailscale_state_folder }}/artis3n-tailscale"

- name: Install | Store state idempotency README
  ansible.builtin.copy:
    src: files/state_readme.md
    dest: "{{ tailscale_state_folder }}/artis3n-tailscale/README.md"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: '0644'

- name: Install | Enable Service
  become: true
  ansible.builtin.service:
    name: "{{ tailscale_service }}"
    state: started
    enabled: true

- name: Install | Fetch Tailscale status
  ansible.builtin.command: tailscale status --json
  changed_when: false
  register: tailscale_status

- name: Install | Parse status JSON
  vars:
    status: "{{ tailscale_status.stdout | from_json }}"
  ansible.builtin.set_fact:
    tailscale_is_online: "{{ status.Self.Online }}"
    tailscale_version: "{{ status.Version }}"

- name: Install | Tailscale version and online status
  ansible.builtin.debug:
    msg: "Ver: {{ tailscale_version }} Online: {{ tailscale_is_online }}"
  when: verbose

- name: Install | Save State
  ansible.builtin.template:
    src: state.j2
    dest: "{{ tailscale_state_folder }}/artis3n-tailscale/state"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: '0644'
  register: state_file

# OAuth key starts with 'tskey-client-', auth key starts with 'tskey-auth-', with headscale it can be 'unused'
- name: Install | Create authkey string
  ansible.builtin.set_fact:
    tailscale_authkey_sting: >-
      {# Check if the key is an OAuth key #}
      {% if tailscale_authkey.startswith('tskey-client-') %}
      {{ tailscale_authkey }}?ephemeral={{ tailscale_ephemeral | bool }}&preauthorized={{ tailscale_preauthorized | bool }}
      {# Check if the key is not OAuth (auth or unuses) #}
      {% else %}
      {{ tailscale_authkey }}
      {% endif %}
  no_log: "{{ not (insecurely_log_authkey | bool) }}"

- name: Install | Bring Tailscale Up
  become: true
  ansible.builtin.command: "tailscale up {{ tailscale_args | trim }} --authkey='{{ tailscale_authkey_sting | trim }}'"
  # Since the auth key is included in this task's output, we do not want to log output
  no_log: "{{ not (insecurely_log_authkey | bool) }}"
  changed_when: true
  register: tailscale_start
  # If a failure occurred due to state changes, we still want to log a redacted version of the error if "no_log" is true
  ignore_errors: true
  when:
    - not tailscale_up_skip
    - state_file is changed or not tailscale_is_online
  notify: Confirm Tailscale is Connected
  async: 60
  poll: 5

- name: Install | Report non-sensitive stdout from "tailscale up"  # noqa: no-handler
  ansible.builtin.debug:
    msg: "{{ tailscale_start.stdout | replace(tailscale_authkey, 'REDACTED') | regex_replace('\\t', '') | split('\n') }}"
  when:
    - tailscale_start is failed
    - tailscale_start.stdout | length > 0
  register: nonsensitive_stdout

- name: Install | Pausing to highlight stdout message above
  ansible.builtin.pause:
    seconds: 5
  when: nonsensitive_stdout is not skipped

- name: Install | Clear State Upon Error
  ansible.builtin.file:
    path: "{{ tailscale_state_folder }}/artis3n-tailscale/state"
    state: absent
  when:
    - tailscale_start is failed

- name: Install | Report redacted failure from "tailscale up"  # noqa: no-handler
  ansible.builtin.fail:
    msg: "{{ tailscale_start.stderr | default () | regex_replace('tskey.*\\s', 'REDACTED ') | regex_replace('\\t', '') | split('\n') }}"
  when:
    - tailscale_start is failed
