---
- name: Uninstall | Check If Tailscale Is Connected
  ansible.builtin.command: tailscale status
  changed_when: false
  failed_when: false
  register: tailscale_status

- name: Uninstall | De-register Tailscale Node
  become: true
  # Hack to get correct changed/ok status
  ansible.builtin.shell: tailscale status; tailscale logout
  register: tailscale_logout
  changed_when: "'Logged out.' not in tailscale_status.stdout and 'not logged in' not in tailscale_status.stdout"
  when:
    # [Errno 2] No such file or directory: 'tailscale'
    - tailscale_status.rc != 2
    # "bash: tailscale: command not found"
    - tailscale_status.rc != 127

- name: Uninstall | Delete Tailscale State
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.artis3n-tailscale"
    state: absent

- name: Uninstall | Gather Service Facts
  ansible.builtin.service_facts:

- name: Uninstall | Disable Tailscale Service
  become: true
  ansible.builtin.service:
    name: "{{ tailscale_service }}"
    state: stopped
    enabled: false
  when: tailscale_service in ansible_facts.services

- name: Uninstall | CentOS and related families
  when: >
    ansible_distribution in tailscale_centos_family_distros
  ansible.builtin.include_tasks: centos/uninstall.yml

- name: Uninstall | Amazon Linux 2
  when:
    - ansible_distribution == 'Amazon'
    - ansible_distribution_major_version | int < 2023
  ansible.builtin.include_tasks: centos/uninstall-legacy.yml

- name: Uninstall | Debian and related families
  when: ansible_distribution in tailscale_debian_family_distros
  ansible.builtin.include_tasks: debian/uninstall.yml

- name: Uninstall | Fedora and related families
  when: >
    ansible_distribution == 'Fedora'
    or (ansible_distribution == 'Amazon' and ansible_distribution_major_version | int >= 2023)
  ansible.builtin.include_tasks: fedora/uninstall.yml

- name: Uninstall | Arch
  when: ansible_distribution == 'Archlinux'
  ansible.builtin.include_tasks: arch/uninstall.yml

- name: Uninstall | OpenSUSE
  when: ansible_distribution in tailscale_opensuse_family_distros
  ansible.builtin.include_tasks: opensuse/uninstall.yml

- name: Uninstall | Remove Tailscale Daemon State and Logs
  become: true
  ansible.builtin.file:
    path: "/var/lib/tailscale"
    state: absent
