name: Security Scans

on:
  pull_request:
  release:
  push:
    branches:
      - main

jobs:
  snyk-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install dependency manager
        run: pipx install poetry

      - name: Set up Python 3.x
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          # Once supported in https://github.com/actions/setup-python/pull/281
#          cache: 'poetry'

      # Snyk needs Python packages to be installed to scan
      - run: poetry install --no-interaction

      - name: Install Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        run: poetry run snyk test --all-projects --dev --severity-threshold=high --sarif-file-output=snyk.sarif
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload dependency results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

      - name: Upload Snyk results to Snyk.io
        run: poetry run snyk monitor --all-projects --dev
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
